//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class selling_permit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public selling_permit()
        {
            this.selling_permit_items = new HashSet<selling_permit_items>();
        }
    
        public int sell_permit_id { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public Nullable<System.DateTime> permit_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<selling_permit_items> selling_permit_items { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
