//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplying_permit_items
    {
        public int supp_permit_id { get; set; }
        public string item_name { get; set; }
        public Nullable<int> amout { get; set; }
        public Nullable<System.DateTime> prod_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual supplying_permit supplying_permit { get; set; }
    }
}
